import { NextResponse } from 'next/server';
import { getDb, ensureSchema } from '@/app/lib/db';
import { setCache } from '@/app/lib/metaApi';
import { invalidateSalesCache } from '@/app/lib/salesCache';

// Bust both caches so next visit reflects the new student immediately
function bustCursosCache() {
  setCache('cursos_list_v10', { data: null, expires_at: 0, stale_until: 0 });
  invalidateSalesCache();
}

export const dynamic = 'force-dynamic';
export const runtime = 'nodejs';

/* ══════════════════════════════════════════════════════════════════════════
   GET /api/alunos/manual?course=<name>
   Returns all manually added students for a course.
   ══════════════════════════════════════════════════════════════════════════ */
export async function GET(request: Request) {
  const { searchParams } = new URL(request.url);
  const course = (searchParams.get('course') || '').trim();

  try {
    await ensureSchema();
    const sql = getDb();
    // LEFT JOIN buyer_profiles so bp_em_dia and bp_proximo_pagamento travel with the student.
    // This eliminates the need for a separate client-side cache lookup for status calculation.
    const rows = course
      ? await sql`
          SELECT ms.*, bp.bp_em_dia, bp.bp_proximo_pagamento, bp.bp_modelo
          FROM manual_students ms
          LEFT JOIN buyer_profiles bp ON LOWER(bp.email) = LOWER(ms.email)
          WHERE ms.course_name = ${course}
          ORDER BY ms.entry_date DESC`
      : await sql`
          SELECT ms.*, bp.bp_em_dia, bp.bp_proximo_pagamento, bp.bp_modelo
          FROM manual_students ms
          LEFT JOIN buyer_profiles bp ON LOWER(bp.email) = LOWER(ms.email)
          ORDER BY ms.entry_date DESC`;

    return NextResponse.json({ students: rows });
  } catch (e: any) {
    return NextResponse.json({ error: e.message }, { status: 500 });
  }
}

/* ══════════════════════════════════════════════════════════════════════════
   POST /api/alunos/manual
   Create a new manual student.

   Body:
   {
     course_name: string,
     name: string,
     email: string,
     phone?: string,
     entry_date: number,           // timestamp ms
     payment_type: 'PIX' | 'CREDIT_CARD',
     total_amount: number,
     installments: number,          // 1 for PIX
     installment_amount: number,
     installment_dates: [           // auto-generated by client
       { due_ms: number, paid: boolean, paid_ms: number | null }
     ],
     notes?: string
   }
   ══════════════════════════════════════════════════════════════════════════ */
export async function POST(request: Request) {
  let body: any;
  try { body = await request.json(); } catch {
    return NextResponse.json({ error: 'Invalid JSON' }, { status: 400 });
  }

  const {
    course_name, name, email, phone = '', entry_date,
    payment_type = 'PIX', total_amount, installments = 1,
    installment_amount, installment_dates = [], notes = '',
    currency = 'BRL', down_payment = 0,
    // buyer_persona fields from Aluno Único modal
    bp_vendedor = '', bp_modelo = '', bp_pagamento = '',
    bp_em_dia = '', bp_valor = '', document = null,
  } = body;

  if (!course_name || !name || !email || !entry_date || !total_amount) {
    return NextResponse.json({ error: 'Campos obrigatórios faltando' }, { status: 400 });
  }

  // Normalize payment_type — allow 'PIX_MENSAL' through as-is; map others
  const dbPayType = payment_type; // store whatever the client sends (PIX, PIX_MENSAL, CREDIT_CARD, PIX_CARTAO)

  try {
    await ensureSchema();
    const sql = getDb();
    const datesJson = JSON.stringify(installment_dates);
    const now = Date.now();
    const rows = (await sql`
      INSERT INTO manual_students
        (course_name, name, email, phone, entry_date, payment_type,
         total_amount, installments, installment_amount, installment_dates,
         notes, currency, down_payment, created_at, updated_at)
      VALUES
        (${course_name}, ${name.toUpperCase()}, ${email.toLowerCase()}, ${phone}, ${entry_date}, ${dbPayType},
         ${total_amount}, ${installments}, ${installment_amount ?? total_amount}, ${datesJson},
         ${notes}, ${currency}, ${down_payment}, ${now}, ${now})
      RETURNING *
    `) as any[];

    // ── UPSERT buyer_profiles if buyer_persona fields were provided ────────
    const hasBp = bp_vendedor || bp_modelo || bp_pagamento || bp_em_dia || bp_valor || document;
    if (hasBp) {
      const bpValorNum = bp_valor ? parseFloat(String(bp_valor).replace(',', '.')) || null : null;
      await sql`
        INSERT INTO buyer_profiles (email, bp_vendedor, bp_modelo, bp_pagamento, bp_em_dia, bp_valor, document)
        VALUES (${email.toLowerCase()},
                ${bp_vendedor || null}, ${bp_modelo || null}, ${bp_pagamento || null},
                ${bp_em_dia || null}, ${bpValorNum}, ${document || null})
        ON CONFLICT (email) DO UPDATE SET
          bp_vendedor  = COALESCE(EXCLUDED.bp_vendedor, buyer_profiles.bp_vendedor),
          bp_modelo    = COALESCE(EXCLUDED.bp_modelo,   buyer_profiles.bp_modelo),
          bp_pagamento = COALESCE(EXCLUDED.bp_pagamento,buyer_profiles.bp_pagamento),
          bp_em_dia    = COALESCE(EXCLUDED.bp_em_dia,   buyer_profiles.bp_em_dia),
          bp_valor     = COALESCE(EXCLUDED.bp_valor,    buyer_profiles.bp_valor),
          document     = COALESCE(EXCLUDED.document,    buyer_profiles.document)
      `;
    }

    bustCursosCache();
    return NextResponse.json({ student: rows[0] }, { status: 201 });
  } catch (e: any) {
    if (e.message?.includes('duplicate') || e.message?.includes('unique')) {
      return NextResponse.json({ error: 'Email já cadastrado neste curso' }, { status: 409 });
    }
    return NextResponse.json({ error: e.message }, { status: 500 });
  }
}
